package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */


public class irsLocation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	
	private java.lang.String name;
	
	private java.lang.Double latitude;
	
	private java.lang.Double longitude;
	public irsLocation() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(java.lang.Double latitude) {
		this.latitude = latitude;
	}

	public java.lang.Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(java.lang.Double longitude) {
		this.longitude = longitude;
	}

	

	public long getDistanceTo(irsLocation location) {
		// Implementation specified by TSPLIB
		// http://www2.iwr.uni-heidelberg.de/groups/comopt/software/TSPLIB95/
		// Euclidean distance (Pythagorean theorem) - not correct when the
		// surface is a sphere
		double latitudeDifference = location.latitude - latitude;
		double longitudeDifference = location.longitude - longitude;
		double distance = Math.sqrt((latitudeDifference * latitudeDifference)
				+ (longitudeDifference * longitudeDifference));
		return (long) (distance * 1000.0 + 0.5);
	}

	@Override
	public String toString() {
		if (name == null) {
			return super.toString();
		}
		return name;
	}
	

	public irsLocation(java.lang.String name, java.lang.Double latitude,
			java.lang.Double longitude) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
	}

}