package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class irsLocationMatrix implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.irsspace.irs.irsLocation startLocation;
	private com.irsspace.irs.irsLocation toLocation;
	private int distance;

	public irsLocationMatrix() {
	}

	public com.irsspace.irs.irsLocation getStartLocation() {
		return this.startLocation;
	}

	public void setStartLocation(com.irsspace.irs.irsLocation startLocation) {
		this.startLocation = startLocation;
	}

	public com.irsspace.irs.irsLocation getToLocation() {
		return this.toLocation;
	}

	public void setToLocation(com.irsspace.irs.irsLocation toLocation) {
		this.toLocation = toLocation;
	}

	public int getDistance() {
		return this.distance;
	}

	public void setDistance(int distance) {
		this.distance = distance;
	}

	public irsLocationMatrix(com.irsspace.irs.irsLocation startLocation,
			com.irsspace.irs.irsLocation toLocation, int distance) {
		this.startLocation = startLocation;
		this.toLocation = toLocation;
		this.distance = distance;
	}

}