package com.irsspace.irs;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class irsSolution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.irsspace.irs.irsVehicle> vehicleList;
	
	private java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> studentList;

	private String score;

	private java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> schoolList;

	private java.util.List<com.irsspace.irs.irsLocationMatrix> locationMatrixList;

	public irsSolution() {
	}

	public java.util.List<com.irsspace.irs.irsVehicle> getVehicleList() {
		return this.vehicleList;
	}

	public void setVehicleList(
			java.util.List<com.irsspace.irs.irsVehicle> vehicleList) {
		this.vehicleList = vehicleList;
	}

	public java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> getStudentList() {
		return this.studentList;
	}

	public void setStudentList(
			java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> studentList) {
		this.studentList = studentList;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(
			String score) {
		this.score = score;
	}

	public java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> getSchoolList() {
		return this.schoolList;
	}

	public void setSchoolList(
			java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> schoolList) {
		this.schoolList = schoolList;
	}

	public java.util.List<com.irsspace.irs.irsLocationMatrix> getLocationMatrixList() {
		return this.locationMatrixList;
	}

	public void setLocationMatrixList(
			java.util.List<com.irsspace.irs.irsLocationMatrix> locationMatrixList) {
		this.locationMatrixList = locationMatrixList;
	}

	public irsSolution(
			java.util.List<com.irsspace.irs.irsVehicle> vehicleList,
			java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> studentList,
			String score,
			java.util.List<com.irsspace.irs.irsPickupDropoffParticulars> schoolList,
			java.util.List<com.irsspace.irs.irsLocationMatrix> locationMatrixList) {
		this.vehicleList = vehicleList;
		this.studentList = studentList;
		this.score = score;
		this.schoolList = schoolList;
		this.locationMatrixList = locationMatrixList;
	}

}